### ISSUE TITLE
Android Fingerprint for react native

### ISSUE THREAD

**Issue by basequatro** [guanaitong/react-native-fingerprint#1]
After configuring simulator fingerprint, and adding     
<uses-permission android:name="android.permission.USE_FINGERPRINT" />
to manifest
Why the fingerprint dialog is not showing for Android?
https://youtu.be/syj3dtD0s2o?t=194
I've only got a toast message.

**Comment by basequatro** [comment]
GATFingerprint.startTouch('fingerprintCallBack','ios propmpt');

Is there any typo?

**Comment by MarsHou** [comment]
@basequatro  Android no fingerprint dialog for System, need custom.
